# fly.toml app configuration file generated for bravenewworld-sparc on 2025-10-06T23:29:11+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bravenewworld-sparc'
primary_region = 'sin'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = "shared-cpu-2x"
  memory = "4gb"

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'

[mounts]
  source="bnw_data"
  destination="/data"