"""
Django settings for geoview project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str(
  "SECRET_KEY", 
  default="django-insecure-h*(nxiefniwybjug6jn6!a*ib(b+1*j1h-yz5dql0r1$@e7o2u",
)

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = env.bool("DEBUG", default=True)  # new

#ALLOWED_HOSTS = ['https://fly.io/apps/processing/monitoring', 'https://processing.fly.dev', 'http://127.0.0.1:8000/']

ALLOWED_HOSTS = ["bravenewworld-sparc.fly.dev", "localhost", "127.0.0.1"]  
CSRF_TRUSTED_ORIGINS = ["https://bravenewworld-sparc.fly.dev"]  

#CSRF_TRUSTED_ORIGINS = ['https://fly.io/apps/processing/monitoring', 'https://processing.fly.dev']


'''
DEBUG = True
ALLOWED_HOSTS = []
'''

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django.contrib.gis",
    "geoApp",
    "whitenoise.runserver_nostatic",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'geoview.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'geoApp', 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                 "django.template.context_processors.debug",
            ],
        },
    },
]

WSGI_APPLICATION = 'geoview.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'geoapp',         # <-- Replace with your database name
        'USER': 'postgres',         # <-- Replace with your database user
        'PASSWORD': 'ku754g93', # <-- Replace with your database password
        'HOST': 'localhost',            # Or your DB host
        'PORT': '5432',                 # Default PostgreSQL port
    },
}

'''
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'bravenewworld',         # <-- Replace with your database name
        'USER': 'ltkdt',         # <-- Replace with your database user
        'PASSWORD': 'ku754g93', # <-- Replace with your database password
        'HOST': 'localhost',            # Or your DB host
        'PORT': '5432',                 # Default PostgreSQL port
    },
}


DATABASES = {
    "default": env.db_url("DATABASE_URL", default="sqlite:///db.sqlite3"),
}
'''

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

#STATIC_URL = 'static/'
STATIC_URL = "static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR,'static'),
                    os.path.join(BASE_DIR,'geoApp', 'templates', 'geoApp')]
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE ="whitenoise.storage.CompressedManifestStaticFilesStorage" 

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'

# Store uploaded media inside the project during development so the
# dev server and local user have a writable location. Previously this
# pointed to '/data/media' which required root access and caused
# PermissionError when admin tried to replace files.
MEDIA_ROOT = BASE_DIR / "media"
